spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/nextdoor?serverTimezone=Europe/Bucharest
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migrate,classpath:db/data
    baselineOnMigrate: true
app:
  jwt:
    secret: test
    accessTokenExpirationInMs: 86400000
    refreshTokenExpirationInMs: 30758400000
