spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/nextdoor?serverTimezone=Europe/Bucharest
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migrate,classpath:db/data
    baselineOnMigrate: true
app:
  jwtSecret: test
  jwtExpirationInMs: 1000
