spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/nextdoor?serverTimezone=Europe/Bucharest
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:db/migrate,classpath:db/data
    baselineOnMigrate: true
app:
  jwtSecret: test
  jwtExpirationInMs: 1000
